### ISSUE TITLE
PDX for dumping system lock key?

### ISSUE THREAD

**Issue by ChaoticPumpkin** [jaames/playdate-reverse-engineering#11]
Hello, I was wondering if someone has made a tool that dumps the lock key as seen at the bottom of [this page](https://github.com/jaames/playdate-reverse-engineering/blob/main/usb/usb.md), I am not very familiar with C so any help would be appreciated!

**Comment by jaames** [comment]
This is left as an "exercise for the reader" since unless you're really sure of what you're doing you can quite easily brick your Playdate if you're messing with unlocked mode serial commands, and I don't want to be responsible for that. Additionally, it is no longer possible to dump the key from firmware 1.11 onwards.

**Comment by jankais3r** [comment]
If anyone stumbles upon this issue in the future, feel free to DM me at [@jankais3r](https://twitter.com/jankais3r) and I will send you a .pdx file that displays your device's unlock key. Works as of 1.12.3.
